platform_url: https://qualysguard.qg5.apps.qualys.com
user: quaysDkb
password: !!binary |
  Z0FBQUFBQnBjeHpWNG5CSThZcHBCNnh6aElJdWcwYmJwaTVCaTdpdDdFeUFnVDFmQ1pXTUdKTnJh
  ZDJYNnRZYTkxcWxtVVctYWM0UjJlX2RBek1ycTU4X2pka2ZDZTh0T0E9PQ==
